In [1]:
!pip install optuna

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 15.6 MB/s eta 0:00:00


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv("../data/cancer-risk-factors.csv")

In [4]:
df.head(5).T

,0,1,2,3,4
Patient_ID,LU0000,LU0001,LU0002,LU0003,LU0004
Cancer_Type,Breast,Prostate,Skin,Colon,Lung
Age,68,74,55,61,67
Gender,0,1,1,0,1
Smoking,7,8,7,6,10
Alcohol_Use,2,9,10,2,7
Obesity,8,8,7,2,4
Family_History,0,0,0,0,0
Diet_Red_Meat,5,0,3,6,6
Diet_Salted_Processed,3,3,3,2,3


In [5]:
X = df.drop(columns=['Risk_Level', 'Patient_ID', 'Cancer_Type'])

In [6]:
le = LabelEncoder()
y = le.fit_transform(df['Risk_Level'])

In [7]:
print(y)

[2 2 2 ... 1 2 2]


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [9]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Decision Tree

In [10]:
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_scaled, y_train)
y_pred_decision_tree = decision_tree.predict(X_test_scaled)

In [11]:
print("Decision Tree Classifier:")
print(classification_report(y_test, y_pred_decision_tree))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_decision_tree))

Decision Tree Classifier:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       0.98      1.00      0.99        65
           2       1.00      1.00      1.00       315

    accuracy                           1.00       400
   macro avg       0.99      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion Matrix:
[[ 20   0   0]
 [  0  65   0]
 [  0   1 314]]


## Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression

logistic_regression = LogisticRegression(random_state=42, max_iter=100)
logistic_regression.fit(X_scaled, y_train)
y_pred_logistic_regression = logistic_regression.predict(X_test_scaled)

In [13]:
print("Logistic Regression:")
print(classification_report(y_test, y_pred_logistic_regression))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_logistic_regression))

Logistic Regression:
              precision    recall  f1-score   support

           0       1.00      0.80      0.89        20
           1       0.97      0.95      0.96        65
           2       0.98      0.99      0.99       315

    accuracy                           0.98       400
   macro avg       0.98      0.92      0.95       400
weighted avg       0.98      0.98      0.98       400

Confusion Matrix:
[[ 16   0   4]
 [  0  62   3]
 [  0   2 313]]


## Remove some X variables

In [14]:
X_new = df.drop(columns=['Risk_Level', 'Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])
le = LabelEncoder()
y_new = le.fit_transform(df['Risk_Level'])

In [15]:
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size=0.2, random_state=42, stratify=y)

In [16]:
scaler = StandardScaler()
X_new_scaled = scaler.fit_transform(X_train_new)
X_test_new_scaled = scaler.transform(X_test_new)

## Decison Tree and Logistic Regression with new X

In [17]:
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_new_scaled, y_train_new)
y_pred_decision_tree_new = decision_tree.predict(X_test_new_scaled)
print("Decision Tree Classifier:")
print(classification_report(y_test_new, y_pred_decision_tree_new))
print("Confusion Matrix:")
print(confusion_matrix(y_test_new, y_pred_decision_tree_new))

Decision Tree Classifier:
              precision    recall  f1-score   support

           0       0.28      0.35      0.31        20
           1       0.55      0.48      0.51        65
           2       0.85      0.86      0.86       315

    accuracy                           0.78       400
   macro avg       0.56      0.56      0.56       400
weighted avg       0.78      0.78      0.77       400

Confusion Matrix:
[[  7   0  13]
 [  0  31  34]
 [ 18  25 272]]


In [18]:
from sklearn.linear_model import LogisticRegression

logistic_regression = LogisticRegression(random_state=42, max_iter=100)
logistic_regression.fit(X_new_scaled, y_train_new)
y_pred_logistic_regression_new = logistic_regression.predict(X_test_new_scaled)
print("Logistic Regression:")
print(classification_report(y_test_new, y_pred_logistic_regression_new))
print("Confusion Matrix:")
print(confusion_matrix(y_test_new, y_pred_logistic_regression_new))

Logistic Regression:
              precision    recall  f1-score   support

           0       0.50      0.20      0.29        20
           1       0.85      0.78      0.82        65
           2       0.91      0.96      0.93       315

    accuracy                           0.89       400
   macro avg       0.75      0.65      0.68       400
weighted avg       0.88      0.89      0.88       400

Confusion Matrix:
[[  4   0  16]
 [  0  51  14]
 [  4   9 302]]


## Smote - Synthetic Minority Over Sampling Technique

In [19]:
X_new = df.drop(columns=['Risk_Level', 'Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])
le = LabelEncoder()
y_new = le.fit_transform(df['Risk_Level'])
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size=0.2, random_state=42, stratify=y)

In [20]:
print(pd.Series(y_train_new).value_counts())

2    1259
1     259
0      82
Name: count, dtype: int64


In [21]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X_train_new, y_train_new)

print(pd.Series(y_smote).value_counts())

2    1259
1    1259
0    1259
Name: count, dtype: int64


## Random Forest - Not Scaled

In [22]:
random_forest = RandomForestClassifier(random_state=42)
random_forest.fit(X_smote, y_smote)
y_pred_random_forest = random_forest.predict(X_test_new)
print("Random Forest Classifier:")
print(classification_report(y_test_new, y_pred_random_forest))
print("Confusion Matrix:")
print(confusion_matrix(y_test_new, y_pred_random_forest))

Random Forest Classifier:
              precision    recall  f1-score   support

           0       0.41      0.35      0.38        20
           1       0.73      0.58      0.65        65
           2       0.88      0.92      0.90       315

    accuracy                           0.84       400
   macro avg       0.67      0.62      0.64       400
weighted avg       0.83      0.84      0.83       400

Confusion Matrix:
[[  7   0  13]
 [  0  38  27]
 [ 10  14 291]]


In [23]:
scaler = StandardScaler()
X_smote_scaled = scaler.fit_transform(X_smote)
X_test_new_scaled = scaler.transform(X_test_new)

## RandomForest - Scaled

In [24]:
random_forest = RandomForestClassifier(random_state=42)
random_forest.fit(X_smote_scaled, y_smote)
y_pred_random_forest = random_forest.predict(X_test_new_scaled)
print("Random Forest Classifier:")
print(classification_report(y_test_new, y_pred_random_forest))
print("Confusion Matrix:")
print(confusion_matrix(y_test_new, y_pred_random_forest))

Random Forest Classifier:
              precision    recall  f1-score   support

           0       0.41      0.35      0.38        20
           1       0.73      0.58      0.65        65
           2       0.88      0.92      0.90       315

    accuracy                           0.84       400
   macro avg       0.67      0.62      0.64       400
weighted avg       0.83      0.84      0.83       400

Confusion Matrix:
[[  7   0  13]
 [  0  38  27]
 [ 10  14 291]]


## Optuna

### 📌 Tổng quan về Cơ chế Tối ưu hóa Siêu tham số với Optuna

1. **Optuna**: Thư viện tự động tìm kiếm siêu tham số thông minh thông qua việc tối ưu hóa một hàm mục tiêu (`objective`).
2. **TPESampler (Tree-structured Parzen Estimator)**: Bộ não thuật toán dựa trên phân phối xác suất Bayesian. Nó chia lịch sử thử nghiệm thành 2 nhóm: *tốt nhất* (high-performing) và *còn lại* (low-performing), từ đó tính toán gợi ý các tham số tiếp theo có xác suất cao nhất rơi vào nhóm tốt và tránh vùng điểm kém.
3. **Trial & Các phương thức Suggest**:
   - `Trial` đại diện cho một lượt thử nghiệm đơn lẻ.
   - `trial.suggest_int()` / `suggest_categorical()`: Các hàm yêu cầu bộ sampler gợi ý giá trị (số nguyên hoặc phân loại) phù hợp cho từng siêu tham số trong không gian tìm kiếm.
4. **StratifiedKFold**: Cơ chế chia dữ liệu K-Phần (K-Fold) giúp đảm bảo tỷ lệ giữa các phân lớp (classes) trong từng phần luôn đồng đều như tập dữ liệu gốc, cực kỳ quan trọng khi xử lý dữ liệu mất cân bằng nhằm đánh giá mô hình khách quan nhất.
5. **Macro F1-Score**: Chỉ số đánh giá bằng cách tính F1-Score riêng biệt cho từng lớp rồi lấy trung bình cộng giản đơn. Khác với F1 thông thường (chỉ dùng cho nhị phân) hay Accuracy/Micro F1 (dễ bị bias bởi lớp chiếm đa số), Macro F1 đánh giá công bằng hiệu năng của mô hình trên tất cả các lớp.

In [25]:
import optuna
from optuna.samplers import TPESampler #Tree-structured Parzen Estimator - "bộ não" quyết định cách chọn tham số tiếp theo.
from sklearn.metrics import classification_report, confusion_matrix, f1_score, make_scorer #??
from sklearn.model_selection import cross_val_score, StratifiedKFold
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
import joblib #save model

In [26]:
# Multiple class
# f1_score thông thường (mặc định là nhị phân - binary)
def macro_f1(y_true, y_pred):
    # average='macro' tính điểm f1_score cho từng class và lấy trung bình cộng thay vì dùng Accuracy
    # hay Micro f1 score chung kia (bị bias)
    return f1_score(y_true, y_pred, average='macro')

scorer = make_scorer(macro_f1, greater_is_better=True)

In [27]:
def objective(trial):
    # Định nghĩa dictionary chứa các hyperparameters cho RandomForestClassifier
    # trial.suggest_int('name', low, high, step)
    # trial.suggest_categorical('name', ['option1', 'option2'])
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300, step=50),
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'entropy', 'log_loss']),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        'class_weight': trial.suggest_categorical('class_weight', ['balanced', 'balanced_subsample', None]),
        'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
    }

    # Khởi tạo mô hình với các tham số từ params
    smote = SMOTE(random_state=42)
    scaler = StandardScaler()
    clf = RandomForestClassifier(**params, random_state=42)
    pl = Pipeline([('smote', smote), ('scaler', scaler), ('clf', clf)])

    # Đánh giá chéo (Cross-validation) sử dụng StratifiedKFold
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = cross_val_score(pl, X_train_new, y_train_new, cv=cv, scoring=scorer, n_jobs=-1)

    # scores = []
    # for train_idx, val_idx in cv.split(X_smote_scaled, y_smote):
    #   X_t, y_t = X_smote_scaled[train_idx], y_smote[train_idx]
    #   X_v, y_v = X_smote_scaled[val_idx], y_smote[val_idx]
    #   clf.fit(X_t, y_t)
    #   y_pred = clf.predict(X_v)
    #   scorer = macro_f1(y_v, y_pred)
    #   score.append(scorer)
    # return scores.mean()

    # Trả về điểm trung bình Macro F1
    return scores.mean()

### 📌 Vai trò của `Study` trong Optuna

`Study` là **cuộc thử nghiệm tổng thể** quản lý toàn bộ quá trình tối ưu hóa:
* **Quản lý mục tiêu:** Định nghĩa hướng tối ưu là cực đại hóa (`maximize`) hay cực tiểu hóa (`minimize`) thông qua hàm `objective`.
* **Lưu trữ lịch sử:** Lưu lại thông tin của tất cả các lượt chạy thử (`Trial`).
* **Tính năng nâng cao (khi dùng `storage` và `study_name`):**
  * **Khôi phục (Resume):** Chạy tiếp tục các lượt thử nghiệm cũ mà không phải làm lại từ đầu (`load_if_exists=True`).
  * **Tối ưu song song:** Cho phép nhiều máy/tiến trình cùng tham gia tối ưu một bài toán thông qua cơ sở dữ liệu chung (RDB).

```
# Khi bạn muốn lưu trữ vào SQLite để sau này tải lại hoặc vẽ đồ thị phân tích:
study = optuna.create_study(
    study_name='rf_macro_f1',
    direction='maximize',
    storage='sqlite:///optuna_studies.db', # Lưu vào file db
    load_if_exists=True # Nếu đã có tên này rồi thì chạy tiếp tục, không ghi đè
)
```

In [28]:
# Khởi tạo và chạy thử nghiệm Optuna
study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42), study_name='rf_macro_f1')
study.optimize(objective, n_trials=50, show_progress_bar=True)

print("Best Trial:")
print("  Value (Macro F1):", study.best_trial.value)
print("  Params:")
for key, value in study.best_trial.params.items():
    print(f"    {key}: {value}")

[I 2026-10-05 09:31:28,551] A new study created in memory with name: rf_macro_f1


  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-10-05 09:31:37,250] Trial 0 finished with value: 0.7071186512829282 and parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 6, 'criterion': 'gini', 'max_features': 'sqrt', 'class_weight': 'balanced_subsample', 'bootstrap': True}. Best is trial 0 with value: 0.7071186512829282.
[I 2026-10-05 09:31:45,420] Trial 1 finished with value: 0.6183413604495076 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 5, 'criterion': 'entropy', 'max_features': None, 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 0 with value: 0.7071186512829282.
[I 2026-10-05 09:31:54,077] Trial 2 finished with value: 0.6533862217279165 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 10, 'criterion': 'gini', 'max_features': 'log2', 'class_weight': 'balanced_subsample', 'bootstrap': True}. Best is trial 0 with value: 0.7071186512829282.
[I 2026-10-05 09:32:05,

In [29]:
best_params = study.best_trial.params
best_params['random_state'] = 42
print(best_params)

{'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 9, 'criterion': 'gini', 'max_features': 'sqrt', 'class_weight': 'balanced_subsample', 'bootstrap': True, 'random_state': 42}


In [30]:
random_forest = RandomForestClassifier(**best_params)
random_forest.fit(X_smote_scaled, y_smote)
y_pred_random_forest = random_forest.predict(X_test_new_scaled)
print("Random Forest Classifier:")
print(classification_report(y_test_new, y_pred_random_forest))
print("Confusion Matrix:")
print(confusion_matrix(y_test_new, y_pred_random_forest))

Random Forest Classifier:
              precision    recall  f1-score   support

           0       0.33      0.45      0.38        20
           1       0.72      0.66      0.69        65
           2       0.89      0.89      0.89       315

    accuracy                           0.83       400
   macro avg       0.65      0.67      0.65       400
weighted avg       0.84      0.83      0.83       400

Confusion Matrix:
[[  9   0  11]
 [  0  43  22]
 [ 18  17 280]]


## XGBoost

In [31]:
from xgboost import XGBClassifier

In [32]:
X_new = df.drop(columns=['Risk_Level', 'Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])
y_new = df['Risk_Level']
le = LabelEncoder()
y_new = le.fit_transform(y)
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size=0.2, random_state=42, stratify=y)

In [33]:
smote = SMOTE(random_state=42)
xgb = XGBClassifier(use_label_encoder=True, eval_metrics='mlogloss', random_state=42, n_jobs=-1)
pl = Pipeline([('smote', smote), ('xgb', xgb)])

pl.fit(X_train_new, y_train_new)
y_pred_xgb = pl.predict(X_test_new)
print("XGBoost Classifier:")
print(classification_report(le.inverse_transform(y_test_new), le.inverse_transform(y_pred_xgb)))
print("Confusion Matrix:")
print(confusion_matrix(le.inverse_transform(y_test_new), le.inverse_transform(y_pred_xgb)))

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [09:35:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "eval_metrics", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBoost Classifier:
              precision    recall  f1-score   support

           0       0.35      0.40      0.37        20
           1       0.77      0.71      0.74        65
           2       0.90      0.91      0.91       315

    accuracy                           0.85       400
   macro avg       0.67      0.67      0.67       400
weighted avg       0.85      0.85      0.85       400

Confusion Matrix:
[[  8   0  12]
 [  0  46  19]
 [ 15  14 286]]


## XGBoost + Optuna

In [34]:
import optuna
from optuna.samplers import TPESampler #Tree-structured Parzen Estimator - "bộ não" quyết định cách chọn tham số tiếp theo.
from sklearn.metrics import classification_report, confusion_matrix, f1_score, recall_score, make_scorer #??
from sklearn.model_selection import cross_val_score, StratifiedKFold
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
import joblib #save model

In [35]:
# Settings
TARGET_LABEL = 'High'
LABEL_ORDER = ['High', 'Medium', 'Low']
N_TRIALS = 50
CV_FOLDS = 5

In [36]:
X_new = df.drop(columns=['Risk_Level', 'Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])
y_new = df['Risk_Level']
le = LabelEncoder()
y_new = le.fit_transform(df.loc[X_new.index, 'Risk_Level'])
print(le.classes_)
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size=0.2, random_state=42, stratify=y)

['High' 'Low' 'Medium']


In [37]:
# Lấy index dạng số của class mục tiêu 'High' trong le.classes_
target_index = np.where(le.classes_ == TARGET_LABEL)[0][0]
print(f'Target index: {target_index}')
print(f'Target label: {le.classes_}')

Target index: 0
Target label: ['High' 'Low' 'Medium']


In [38]:
# Lay value recall moi thang High-Risk
def macro_recall(y_true, y_pred):
    return recall_score(y_true, y_pred, average=None, labels=list(range(len(le.classes_))))[target_index]

scorer_recall = make_scorer(macro_recall, greater_is_better=True)

def objective_xgb(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300, step=50),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 5.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        'random_state': 42,
        'n_jobs': -1,
        'eval_metric': 'mlogloss',
        'objective': 'multi:softmax',
        'use_label_encoder': False,
        'num_class': len(LABEL_ORDER)
    }

    smote = SMOTE(random_state=42)
    scaler = StandardScaler()
    clf = XGBClassifier(**params)

    pl = Pipeline([('smote', smote), ('scaler', scaler), ('clf', clf)])

    cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=42)
    scores = cross_val_score(pl, X_train_new, y_train_new, cv=cv, scoring=scorer_recall, n_jobs=-1)

    return scores.mean()

In [41]:
study = optuna.create_study(study_name='xgb_macro_recall', direction='maximize', sampler=TPESampler(seed=42))
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Best Trial:")
print("  Value (Macro Recall):", study.best_trial.value)
print("  Params:")
for key, value in study.best_trial.params.items():
    print(f"    {key}: {value}")

[I 2026-10-05 09:44:09,329] A new study created in memory with name: xgb_macro_recall


  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-10-05 09:44:16,497] Trial 0 finished with value: 0.7071186512829282 and parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 6, 'criterion': 'gini', 'max_features': 'sqrt', 'class_weight': 'balanced_subsample', 'bootstrap': True}. Best is trial 0 with value: 0.7071186512829282.
[I 2026-10-05 09:44:25,374] Trial 1 finished with value: 0.6183413604495076 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 5, 'criterion': 'entropy', 'max_features': None, 'class_weight': 'balanced', 'bootstrap': True}. Best is trial 0 with value: 0.7071186512829282.
[I 2026-10-05 09:44:33,164] Trial 2 finished with value: 0.6533862217279165 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 10, 'criterion': 'gini', 'max_features': 'log2', 'class_weight': 'balanced_subsample', 'bootstrap': True}. Best is trial 0 with value: 0.7071186512829282.
[I 2026-10-05 09:44:40,

In [42]:
best_params = study.best_trial.params
best_params['random_state'] = 42

smote = SMOTE(random_state=42)
scaler = StandardScaler()
xgb = XGBClassifier(**best_params)
pipe = Pipeline([('smote', smote), ('scaler', scaler), ('xgb', xgb)])

pipe.fit(X_train_new, y_train_new)
y_pred_xgb = pipe.predict(X_test_new)
print("XGBoost Classifier:")
print(classification_report(le.inverse_transform(y_test_new), le.inverse_transform(y_pred_xgb)))
print("Confusion Matrix:")
print(confusion_matrix(le.inverse_transform(y_test_new), le.inverse_transform(y_pred_xgb)))

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [09:47:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "bootstrap", "class_weight", "criterion", "max_features", "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBoost Classifier:
              precision    recall  f1-score   support

        High       0.43      0.45      0.44        20
         Low       0.75      0.66      0.70        65
      Medium       0.90      0.92      0.91       315

    accuracy                           0.85       400
   macro avg       0.69      0.68      0.68       400
weighted avg       0.85      0.85      0.85       400

Confusion Matrix:
[[  9   0  11]
 [  0  43  22]
 [ 12  14 289]]


## XGBoost + Class-Weight

In [43]:
X_new = df.drop(columns=['Risk_Level', 'Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])
y_new = df['Risk_Level']
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size=0.2, random_state=42, stratify=y)

In [46]:
le = LabelEncoder()
y_train_new = le.fit_transform(df.loc[X_train_new.index, 'Risk_Level'])
y_test_new = le.transform(df.loc[X_test_new.index, 'Risk_Level'])
print(le.classes_)
classes, counts = np.unique(y_train_new, return_counts=True)
print(classes, counts)
classes_weight = {cl: max(counts)/count for cl, count in zip(classes, counts)}
print(classes_weight)
sample_weight = np.array([classes_weight[cl] for cl in y_train_new])
print(sample_weight)

['High' 'Low' 'Medium']
[0 1 2] [  82  259 1259]
{np.int64(0): np.float64(15.353658536585366), np.int64(1): np.float64(4.861003861003861), np.int64(2): np.float64(1.0)}
[1. 1. 1. ... 1. 1. 1.]


In [47]:
xgb_weighted = XGBClassifier(
    objective='multi:softmax',
    num_class=len(classes),
    eval_metric='mlogloss',
    random_state=42,
    n_estimators=105,
    max_depth=3,
    learning_rate=0.014843806162322944,
    subsample=0.7730982444721965,
    colsample_bytree=0.8509237341976973,
    gamma=4.134336554829186,
    reg_alpha=4.453508368364819,
    reg_lambda=2.616923339470738,
    n_jobs=-1
)

pipe = Pipeline([('xgb', xgb_weighted)])

pipe.fit(X_train_new, y_train_new, xgb__sample_weight=sample_weight)
y_pred_xgb = pipe.predict(X_test_new)

print("XGBoost Classifier:")
print(classification_report(y_test_new, y_pred_xgb))
print("Confusion Matrix:")
print(confusion_matrix(y_test_new, y_pred_xgb))

XGBoost Classifier:
              precision    recall  f1-score   support

           0       0.21      0.75      0.33        20
           1       0.43      0.80      0.56        65
           2       0.91      0.60      0.72       315

    accuracy                           0.64       400
   macro avg       0.52      0.72      0.54       400
weighted avg       0.80      0.64      0.68       400

Confusion Matrix:
[[ 15   0   5]
 [  0  52  13]
 [ 56  70 189]]


## XGBoost + Class-Weight + Optuna

In [65]:
def macro_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='macro')

scorer = make_scorer(macro_f1, greater_is_better=True)

def objective_xgb_weighted(trial):
    # 1. Định nghĩa các siêu tham số cần tối ưu cho XGBoost
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 400),
        'max_depth': trial.suggest_int('max_depth', 2, 12),
        'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'gamma': trial.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 5.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        'use_label_encoder': False,
        'eval_metric': 'mlogloss',
    }

    xgb_weighted = XGBClassifier(**params)
    scores = []

    cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=42)
    for train_idx, val_idx in cv.split(X_train_new, y_train_new):
      X_t, y_t = X_train_new.iloc[train_idx], y_train_new[train_idx]
      X_v, y_v = X_train_new.iloc[val_idx], y_train_new[val_idx]

      # class weight cho cv se khac cho toan bo nen he so se khac
      classes, counts = np.unique(y_t, return_counts=True)
      classes_weight = {cl: max(counts)/count for cl, count in zip(classes, counts)}
      sample_weight = np.array([classes_weight[cl] for cl in y_t])

      xgb_weighted.fit(X_t, y_t, sample_weight=sample_weight)
      y_pred = xgb_weighted.predict(X_v)
      scorer = macro_f1(y_v, y_pred)
      scores.append(scorer)

    return np.mean(scores)

In [66]:
study = optuna.create_study(study_name='xgb_macro_f1', direction='maximize', sampler=TPESampler(seed=42))
study.optimize(objective_xgb_weighted, n_trials=40, show_progress_bar=True)

print("Best Trial:")
print("  Value (Macro Recall):", study.best_trial.value)
print("  Params:")
for key, value in study.best_trial.params.items():
    print(f"    {key}: {value}")

[I 2026-10-05 10:27:15,429] A new study created in memory with name: xgb_macro_f1


  0%|          | 0/40 [00:00<?, ?it/s]

/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:19,015] Trial 0 finished with value: 0.6842784646293902 and parameters: {'n_estimators': 181, 'max_depth': 12, 'learning_rate': 0.06504856968981275, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.4936111842654619, 'gamma': 0.7799726016810132, 'reg_alpha': 0.2904180608409973, 'reg_lambda': 4.330880728874676}. Best is trial 0 with value: 0.6842784646293902.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:24,208] Trial 1 finished with value: 0.6675013314877343 and parameters: {'n_estimators': 260, 'max_depth': 9, 'learning_rate': 0.001124579825911934, 'subsample': 0.9879639408647978, 'colsample_bytree': 0.899465584480253, 'gamma': 1.0616955533913808, 'reg_alpha': 0.9091248360355031, 'reg_lambda': 0.9170225492671691}. Best is trial 0 with value: 0.6842784646293902.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:26,345] Trial 2 finished with value: 0.6877977733661276 and parameters: {'n_estimators': 156, 'max_depth': 7, 'learning_rate': 0.01174843954800703, 'subsample': 0.7164916560792167, 'colsample_bytree': 0.7671117368334277, 'gamma': 0.6974693032602092, 'reg_alpha': 1.4607232426760908, 'reg_lambda': 1.8318092164684585}. Best is trial 2 with value: 0.6877977733661276.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:32,301] Trial 3 finished with value: 0.6882746279696963 and parameters: {'n_estimators': 210, 'max_depth': 10, 'learning_rate': 0.003123317753376431, 'subsample': 0.8056937753654446, 'colsample_bytree': 0.7554487413172255, 'gamma': 0.23225206359998862, 'reg_alpha': 3.0377242595071916, 'reg_lambda': 0.8526206184364576}. Best is trial 3 with value: 0.6882746279696963.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:32,922] Trial 4 finished with value: 0.6898128527752851 and parameters: {'n_estimators': 72, 'max_depth': 12, 'learning_rate': 0.24659691172104828, 'subsample': 0.9233589392465844, 'colsample_bytree': 0.5827682615040224, 'gamma': 0.48836057003191935, 'reg_alpha': 3.4211651325607844, 'reg_lambda': 2.2007624686980067}. Best is trial 4 with value: 0.6898128527752851.


/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[I 2026-10-05 10:27:34,026] Trial 5 finished with value: 0.6500295409415856 and parameters: {'n_estimators': 92, 'max_depth': 7, 'learning_rate': 0.0012167028814593455, 'subsample': 0.9637281608315128, 'colsample_bytree': 0.5552679889600102, 'gamma': 3.31261142176991, 'reg_alpha': 1.5585553804470549, 'reg_lambda': 2.600340105889054}. Best is trial 4 with value: 0.6898128527752851.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:34,995] Trial 6 finished with value: 0.6857496474575436 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.25221951700214285, 'subsample': 0.9100531293444458, 'colsample_bytree': 0.9636993649385135, 'gamma': 4.474136752138244, 'reg_alpha': 2.9894998940554256, 'reg_lambda': 4.609371175115584}. Best is trial 4 with value: 0.6898128527752851.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:35,638] Trial 7 finished with value: 0.6018532427374003 and parameters: {'n_estimators': 81, 'max_depth': 4, 'learning_rate': 0.001294295611551122, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6332063738136893, 'gamma': 1.3567451588694794, 'reg_alpha': 4.143687545759647, 'reg_lambda': 1.7837666334679465}. Best is trial 4 with value: 0.6898128527752851.


/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[I 2026-10-05 10:27:36,883] Trial 8 finished with value: 0.6071724103823031 and parameters: {'n_estimators': 148, 'max_depth': 7, 'learning_rate': 0.0022340165853190056, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 3.861223846483287, 'reg_lambda': 0.993578407670862}. Best is trial 4 with value: 0.6898128527752851.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:37,903] Trial 9 finished with value: 0.6862333181930735 and parameters: {'n_estimators': 51, 'max_depth': 10, 'learning_rate': 0.0563600475052774, 'subsample': 0.8916028672163949, 'colsample_bytree': 0.8627622080115674, 'gamma': 0.3702232586704518, 'reg_alpha': 1.7923286427213632, 'reg_lambda': 0.5793452976256486}. Best is trial 4 with value: 0.6898128527752851.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:38,995] Trial 10 finished with value: 0.7212679697760809 and parameters: {'n_estimators': 211, 'max_depth': 12, 'learning_rate': 0.17240853799881856, 'subsample': 0.6029292565390199, 'colsample_bytree': 0.469482334336557, 'gamma': 1.2256329299294553, 'reg_alpha': 2.0990338245957707, 'reg_lambda': 1.325111957475132}. Best is trial 10 with value: 0.7212679697760809.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:39,727] Trial 11 finished with value: 0.7117548140057834 and parameters: {'n_estimators': 63, 'max_depth': 10, 'learning_rate': 0.11034752086431814, 'subsample': 0.7997802411404783, 'colsample_bytree': 0.6272009983519344, 'gamma': 0.7819024766798157, 'reg_alpha': 4.194577265764127, 'reg_lambda': 2.258040806532418}. Best is trial 10 with value: 0.7212679697760809.


/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest

[I 2026-10-05 10:27:40,425] Trial 12 finished with value: 0.7148429722866063 and parameters: {'n_estimators': 106, 'max_depth': 12, 'learning_rate': 0.26501210068446507, 'subsample': 0.6087633980559807, 'colsample_bytree': 0.4329834446611378, 'gamma': 1.7123669984465388, 'reg_alpha': 2.13350898954304, 'reg_lambda': 0.4723436696370986}. Best is trial 10 with value: 0.7212679697760809.


/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[I 2026-10-05 10:27:41,327] Trial 13 finished with value: 0.709122206849535 and parameters: {'n_estimators': 177, 'max_depth': 12, 'learning_rate': 0.2226911109622686, 'subsample': 0.6246253800637714, 'colsample_bytree': 0.47380109988692504, 'gamma': 1.7445044313873757, 'reg_alpha': 3.8523471732022414, 'reg_lambda': 1.4218632587435307}. Best is trial 10 with value: 0.7212679697760809.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:43,960] Trial 14 finished with value: 0.7018296515321094 and parameters: {'n_estimators': 145, 'max_depth': 11, 'learning_rate': 0.25464218617814266, 'subsample': 0.6555513954996646, 'colsample_bytree': 0.4539974108311835, 'gamma': 1.5807675063988065, 'reg_alpha': 2.1539082843422563, 'reg_lambda': 0.25435664877148034}. Best is trial 10 with value: 0.7212679697760809.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:44,943] Trial 15 finished with value: 0.6983777465974266 and parameters: {'n_estimators': 54, 'max_depth': 12, 'learning_rate': 0.14194885777805724, 'subsample': 0.6676703828115504, 'colsample_bytree': 0.488983543872071, 'gamma': 2.531798096257776, 'reg_alpha': 1.8802349423537237, 'reg_lambda': 1.869716526645924}. Best is trial 10 with value: 0.7212679697760809.


/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[I 2026-10-05 10:27:46,179] Trial 16 finished with value: 0.6686815376755891 and parameters: {'n_estimators': 112, 'max_depth': 11, 'learning_rate': 0.04048724984703099, 'subsample': 0.6605874556003846, 'colsample_bytree': 0.4429524811127294, 'gamma': 1.2846843037628497, 'reg_alpha': 0.7209545191751046, 'reg_lambda': 0.2078676870365912}. Best is trial 10 with value: 0.7212679697760809.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:47,467] Trial 17 finished with value: 0.7255609222184722 and parameters: {'n_estimators': 181, 'max_depth': 10, 'learning_rate': 0.0950283838568537, 'subsample': 0.6079915824760236, 'colsample_bytree': 0.5076247241344374, 'gamma': 1.1941341588571952, 'reg_alpha': 1.868004368414577, 'reg_lambda': 1.3684271491465183}. Best is trial 17 with value: 0.7255609222184722.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:48,645] Trial 18 finished with value: 0.7250708440968996 and parameters: {'n_estimators': 238, 'max_depth': 10, 'learning_rate': 0.13839562794034263, 'subsample': 0.680810677984237, 'colsample_bytree': 0.5491466218756783, 'gamma': 1.7743513899001377, 'reg_alpha': 2.8023087355420584, 'reg_lambda': 1.223157521935577}. Best is trial 17 with value: 0.7255609222184722.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:49,911] Trial 19 finished with value: 0.7202239666528827 and parameters: {'n_estimators': 168, 'max_depth': 10, 'learning_rate': 0.06443594388561877, 'subsample': 0.7014179483611713, 'colsample_bytree': 0.5023355613942864, 'gamma': 1.1824219310803055, 'reg_alpha': 2.9914413814609673, 'reg_lambda': 2.439710588308126}. Best is trial 17 with value: 0.7255609222184722.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:51,434] Trial 20 finished with value: 0.7284181433687771 and parameters: {'n_estimators': 258, 'max_depth': 11, 'learning_rate': 0.10536359355756923, 'subsample': 0.7059775509483422, 'colsample_bytree': 0.6344286005437955, 'gamma': 0.9294696952525748, 'reg_alpha': 3.0639529131086656, 'reg_lambda': 1.8438903944859368}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:52,705] Trial 21 finished with value: 0.7132905851607845 and parameters: {'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.08423176292499877, 'subsample': 0.6894094495991633, 'colsample_bytree': 0.40830376866024587, 'gamma': 0.8975438556624785, 'reg_alpha': 2.61568426188835, 'reg_lambda': 0.9980867262887828}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:54,312] Trial 22 finished with value: 0.7207666259905087 and parameters: {'n_estimators': 230, 'max_depth': 11, 'learning_rate': 0.05645006618358118, 'subsample': 0.7131611040234579, 'colsample_bytree': 0.6192426975337816, 'gamma': 1.5014543507850053, 'reg_alpha': 1.7532321551201215, 'reg_lambda': 0.8511005550084252}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:57,801] Trial 23 finished with value: 0.7108074654763621 and parameters: {'n_estimators': 291, 'max_depth': 11, 'learning_rate': 0.18982927033391273, 'subsample': 0.7286125095565779, 'colsample_bytree': 0.536309427287439, 'gamma': 1.6682473094672676, 'reg_alpha': 1.9410640985124639, 'reg_lambda': 1.4676302779523351}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:27:59,658] Trial 24 finished with value: 0.7065157364284238 and parameters: {'n_estimators': 214, 'max_depth': 8, 'learning_rate': 0.027121610167371555, 'subsample': 0.6005594385310983, 'colsample_bytree': 0.5006131328960064, 'gamma': 1.2459951951844346, 'reg_alpha': 2.563015717629248, 'reg_lambda': 0.9729217257479762}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:27:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:00,858] Trial 25 finished with value: 0.7160099748772287 and parameters: {'n_estimators': 213, 'max_depth': 11, 'learning_rate': 0.11914876296655416, 'subsample': 0.6950672861593477, 'colsample_bytree': 0.655953272346764, 'gamma': 2.205093857009263, 'reg_alpha': 3.1721735708623426, 'reg_lambda': 0.8425687375237421}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:03,641] Trial 26 finished with value: 0.7040564047100792 and parameters: {'n_estimators': 252, 'max_depth': 10, 'learning_rate': 0.04441519067098998, 'subsample': 0.6185216431448209, 'colsample_bytree': 0.5597885161119831, 'gamma': 0.24529582386058402, 'reg_alpha': 1.0543225380843133, 'reg_lambda': 1.7785366723872096}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:05,332] Trial 27 finished with value: 0.717663472277214 and parameters: {'n_estimators': 266, 'max_depth': 12, 'learning_rate': 0.07832538036115286, 'subsample': 0.7289776955132767, 'colsample_bytree': 0.50096857985108, 'gamma': 0.9904894001705845, 'reg_alpha': 2.7320661861482707, 'reg_lambda': 1.1560286968794815}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:07,058] Trial 28 finished with value: 0.7227309708421538 and parameters: {'n_estimators': 301, 'max_depth': 11, 'learning_rate': 0.10771560661571968, 'subsample': 0.6203947320107389, 'colsample_bytree': 0.4542199209015744, 'gamma': 0.8131645948559323, 'reg_alpha': 1.9633119105960204, 'reg_lambda': 1.6004119938922154}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:10,559] Trial 29 finished with value: 0.7175516681917166 and parameters: {'n_estimators': 220, 'max_depth': 10, 'learning_rate': 0.14102436742979801, 'subsample': 0.6302895525205611, 'colsample_bytree': 0.4311075329556544, 'gamma': 0.7502663247050906, 'reg_alpha': 1.6980834166417087, 'reg_lambda': 2.557289656455569}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:11,911] Trial 30 finished with value: 0.707579620183272 and parameters: {'n_estimators': 220, 'max_depth': 9, 'learning_rate': 0.13983513067883874, 'subsample': 0.6530945346619095, 'colsample_bytree': 0.48945853631695657, 'gamma': 0.6584121708881177, 'reg_alpha': 1.9930133062051132, 'reg_lambda': 1.5569024691475732}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:13,740] Trial 31 finished with value: 0.723578318092293 and parameters: {'n_estimators': 293, 'max_depth': 11, 'learning_rate': 0.07311956214932626, 'subsample': 0.6289782479547998, 'colsample_bytree': 0.4889455141688276, 'gamma': 1.1308225533464515, 'reg_alpha': 0.8830769903088247, 'reg_lambda': 1.2159530125324347}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:15,517] Trial 32 finished with value: 0.7190268628696482 and parameters: {'n_estimators': 254, 'max_depth': 10, 'learning_rate': 0.04995241126672503, 'subsample': 0.6876616149353145, 'colsample_bytree': 0.4722806200134753, 'gamma': 1.3278896993698694, 'reg_alpha': 2.380143192798691, 'reg_lambda': 0.9874144216922369}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:17,398] Trial 33 finished with value: 0.6971879101017479 and parameters: {'n_estimators': 271, 'max_depth': 12, 'learning_rate': 0.07665103879114356, 'subsample': 0.6623338807781393, 'colsample_bytree': 0.44258086877989905, 'gamma': 0.5398709642741129, 'reg_alpha': 1.2380838109947292, 'reg_lambda': 1.6524282337130305}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:19,304] Trial 34 finished with value: 0.7081749376448616 and parameters: {'n_estimators': 277, 'max_depth': 10, 'learning_rate': 0.0632209472668123, 'subsample': 0.6879000394343486, 'colsample_bytree': 0.5305136445025329, 'gamma': 1.0043913836286016, 'reg_alpha': 0.04190140797686348, 'reg_lambda': 1.0668340857711216}. Best is trial 20 with value: 0.7284181433687771.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:23,131] Trial 35 finished with value: 0.7313066455210327 and parameters: {'n_estimators': 260, 'max_depth': 11, 'learning_rate': 0.06590577336432804, 'subsample': 0.6514465904887482, 'colsample_bytree': 0.4827918762525874, 'gamma': 1.498462222464858, 'reg_alpha': 0.9826959320211304, 'reg_lambda': 1.5819352328509684}. Best is trial 35 with value: 0.7313066455210327.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:24,824] Trial 36 finished with value: 0.7239166914596338 and parameters: {'n_estimators': 277, 'max_depth': 11, 'learning_rate': 0.12387286078063682, 'subsample': 0.6886151224212187, 'colsample_bytree': 0.547320395351846, 'gamma': 0.3869031764734917, 'reg_alpha': 3.3755021853343514, 'reg_lambda': 1.6038500370315196}. Best is trial 35 with value: 0.7313066455210327.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:26,255] Trial 37 finished with value: 0.7205396103027951 and parameters: {'n_estimators': 275, 'max_depth': 12, 'learning_rate': 0.11551355660699468, 'subsample': 0.6717727101598435, 'colsample_bytree': 0.4248881310906546, 'gamma': 1.310371427647964, 'reg_alpha': 2.194872705717262, 'reg_lambda': 1.09217570455677}. Best is trial 35 with value: 0.7313066455210327.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:27,266] Trial 38 finished with value: 0.7074674368568588 and parameters: {'n_estimators': 119, 'max_depth': 9, 'learning_rate': 0.07721019620285259, 'subsample': 0.611047478900963, 'colsample_bytree': 0.49047359060525697, 'gamma': 1.5951071315856904, 'reg_alpha': 1.6661099328607603, 'reg_lambda': 1.7169257605456993}. Best is trial 35 with value: 0.7313066455210327.


/tmp/ipykernel_1796/3389127331.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [10:28:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:794: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, it

[I 2026-10-05 10:28:28,742] Trial 39 finished with value: 0.7252631878967999 and parameters: {'n_estimators': 269, 'max_depth': 11, 'learning_rate': 0.08583602433873457, 'subsample': 0.6975089649342218, 'colsample_bytree': 0.4723456689275969, 'gamma': 1.6933013090171245, 'reg_alpha': 0.9309144561618029, 'reg_lambda': 0.6826373863220995}. Best is trial 35 with value: 0.7313066455210327.
Best Trial:
  Value (Macro Recall): 0.7313066455210327
  Params:
    n_estimators: 260
    max_depth: 11
    learning_rate: 0.06590577336432804
    subsample: 0.6514465904887482
    colsample_bytree: 0.4827918762525874
    gamma: 1.498462222464858
    reg_alpha: 0.9826959320211304
    reg_lambda: 1.5819352328509684


In [67]:
best_params = study.best_trial.params
best_params['random_state'] = 42
best_params['objective'] = 'multi:softmax'
best_params['num_class'] = len(np.unique(y_train_new))
best_params['eval_metric'] = 'mlogloss'

xgb_weighted = XGBClassifier(**best_params)

xgb_weighted.fit(X_train_new, y_train_new, sample_weight=sample_weight)
y_pred_xgb = xgb_weighted.predict(X_test_new)

print("XGBoost Classifier:")
print(classification_report(y_test_new, y_pred_xgb))
print("Confusion Matrix:")
print(confusion_matrix(y_test_new, y_pred_xgb))

XGBoost Classifier:
              precision    recall  f1-score   support

           0       0.50      0.45      0.47        20
           1       0.75      0.83      0.79        65
           2       0.93      0.91      0.92       315

    accuracy                           0.88       400
   macro avg       0.73      0.73      0.73       400
weighted avg       0.88      0.88      0.88       400

Confusion Matrix:
[[  9   0  11]
 [  0  54  11]
 [  9  18 288]]


In [68]:
joblib.dump(xgb_weighted, 'xgb_weighted.pkl')
print("Model save successfully")

Model save successfully


In [69]:
import joblib
artifacts = {
    'model': xgb_weighted,
    'scaler': scaler,
    'label_encoder': le
}

joblib.dump(artifacts, '../models/xgb_complete_pipeline.pkl')
print("Đã lưu thành công model, scaler và label_encoder vào file 'xgb_complete_pipeline.pkl'!")

Đã lưu thành công model, scaler và label_encoder vào file 'xgb_complete_pipeline.pkl'!
